Result.ok() method
keithasaurus/koda pull request #7
Opened 2022-02-08 10:38 UTC by monomonedula

Simple shortcut to check if an object is an Err or Ok. 

I was missing it since I am using koda with python 3.9 and there's no structural pattern matching so i had to call `isinstance` every time

2022-02-08 17:26 UTC, keithasaurus requested changes
Thanks for the PR! Please excuse the fact that there isn't a lot of guidance built into PRs yet.

I think this could be useful in the context of brevity, but first I want to suggest a few changes:
- `ok` -> `is_ok`: this conveys that we are checking what something is, whereas `ok` alone seems ambiguous to me
- make sure the method returns a type guard, and that it type checks: https://mypy.readthedocs.io/en/latest/type_narrowing.html#typeguards-as-methods
- making the method a property. The result is static, so there's no need to call it. (I'm not sure if needs to be a method/property because we're using a typeguard, or if could just be a static value on the class)

If we don't add the type guard, I don't think this will type check:
```python3
result: Result[int, str] = get_result_func()

if result.is_ok:   # if this is just a `bool` without a typeguard, we don't learn anything about the type of `val`
   print(result.val + 5)
else:
   print("the message is" + result.val)
```

Also:
- needs tests
- we'd want to make sure the same thing is done for `Maybe`: probably `.is_just`
- needs docs

The reason this would need to be mentioned in the docs, in my opinion, is that it's doing something with type narrowing that isn't standard in Python type hints: using a boolean to act as a type guard.

Again, apologies for the lack of automated feedback here. In the near term, I'm planning to:
- make a PR template
- require code coverage threshold of ~100%, so new changes require tests

2022-02-09 08:11 UTC, monomonedula commented
@keithasaurus yep, I agree. However, using `TypeGuard` requires python >=3.10 . Any ideas for a workaround?

2022-02-10 07:19 UTC, keithasaurus commented
No, not a lot of great ideas there. The irony of type guards being only available in 3.10+ is that IMO structural pattern matching is usually going to be nicer that using an `is_ok` type guard anyway.

I don't personally think there's much value in `is_ok` without being a type guard, because usually when you're checking if something is `Ok` or `Err`, you want to do something with the contained value and you can't do that in a type-safe way without also checking the instance type.

On another note, the thing I do like about `isinstance` and `match` are that it's clear the `Ok`/`Err` type is being inspected/established, whereas I'm not sure if that would be as clear with `is_ok`. So I don't feel like the current API is a big problem.

2022-02-10 07:35 UTC, monomonedula commented
@keithasaurus ok then.

2022-02-10 07:35 UTC, closed without merging